apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloakx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: keycloakx
    repoURL: https://codecentric.github.io/helm-charts
    targetRevision: 7.0.1
    helm:
      # https://github.com/codecentric/helm-charts/blob/master/charts/keycloakx/values.yaml
      valuesObject:
        replicas: 1
        command:
          - "/opt/keycloak/bin/kc.sh"
          - "-v"
          - "start"
          - "--hostname=localhost"
        # doesn't have revisionHistoryLimitCount: 0

        # Use environment variables instead
        #for test
#        extraContainers: |
#          - name: postgres-test
#            image: bitnamilegacy/postgresql
#            imagePullPolicy: IfNotPresent
#            env:
#              - name: POSTGRES_DB
#                value: keycloak
#              - name: POSTGRES_USER
#                value: postgres
#              - name: POSTGRES_PASSWORD
#                value: strongpass
#            ports:
#              - containerPort: 5432
#                name: postgres

        extraEnv: |
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_CACHE
            value: local
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: admin
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            value: adminpassword
          - name: KC_DB_URL
            value: "jdbc:sqlserver://mssql.mssql.svc.cluster.local:1433;databaseName=codecentric_keycloakx;encrypt=false;trustServerCertificate=true;"
          - name: KC_DB_USERNAME
            value: sa
          - name: KC_DB
            value: mssql
          - name: KC_DB_PASSWORD
            value: YourStrong@Password123
        #          - name: KC_DB_URL
        #            value: jdbc:postgresql://localhost:5432/keycloak
        #          - name: KC_DB_USERNAME
        #            value: postgres
        #          - name: KC_DB
        #            value: postgres
        #          - name: KC_DB_PASSWORD
        #            value: strongpass

#        ingress:
#          enabled: true
#          className: nginx
#          annotations:
#            kubernetes.io/ingress.class: nginx
#            nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
#            nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "128k"
#            nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
#
#          rules:
#            - host: authx.dracie.tuev-nord.de
        resources:
          requests:
            cpu: "20m"
            memory: "570Mi"
          limits:
            cpu: "400m"
            memory: "1140Mi"

        topologySpreadConstraints: | #verify components
          - topologyKey: topology.kubernetes.io/zone
            maxSkew: 1
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: keycloak
          - topologyKey: kubernetes.io/hostname
            maxSkew: 1
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: keycloak

        podDisruptionBudget: #verify components
          enabled: true
          minAvailable: 1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
